version: '3'

services:
    joplin_db:
        image: postgres:13.1
        container_name: joplin-db
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
        expose:
            - "5432"
        restart: unless-stopped
        environment:
            - POSTGRES_PASSWORD=dbpass
            - POSTGRES_USER=dbuser
            - POSTGRES_DB=joplindb
    joplin:
        image: joplin/server:latest
        container_name: joplin
        depends_on:
            - joplin_db
        expose:
            - "22300"
        restart: unless-stopped
        environment:
            - APP_PORT=22300
            - APP_BASE_URL=${JOPLIN_BASE_URL}
            - DB_CLIENT=pg
            - POSTGRES_PASSWORD=dbpass
            - POSTGRES_DATABASE=joplindb
            - POSTGRES_USER=dbuser
            - POSTGRES_PORT=5432
            - POSTGRES_HOST=joplin_db

networks:
  default:
    name: primary
    external: true