version: "3"

# To add some security all the services can be exposed internally and proxied by a reverse proxy service
# This network will isolate the environment for protection
# This can also be done directly with:
#     $ docker network create -d bridge primary
networks:
  primary:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/16
        # gateway: 172.22.0.1
