version: "3"

services:
  homer:
    image: b4bz/homer
    container_name: homer
    restart: unless-stopped
    environment:
      - UID=1000
      - GID=1000
    expose:
      - "8080"
    volumes:
      - ./assets/:/www/assets

networks:
  default:
    external:
      name: primary