version: '2'

services:
  glances:
    image: nicolargo/glances
    restart: always
    container_name: glances
    environment:
      - GLANCES_OPT=-w
    pid: "host"
    expose:
      - '61208'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    name: primary
    external: true
