version: "3.7"

services:
  jenkins:
    image: jenkins/jenkins
    container_name: jenkins
    restart: unless-stopped
    user: root
    environment:
      - TZ=Europe/Madrid
      - JENKINS_USER=0
      - JENKINS_OPTS="--httpPort=11000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # Only if it is necessary to manage docker from this jenkins instance
      - /usr/bin/docker:/usr/bin/docker # Only if it is necessary to manage docker from this jenkins instance
    ports:
      - '11000:11000'
      # - '50000' # Only if TCP Agent Listener Port is necessary

networks:
  default:
    name: primary
    external: true
