version: "2.1"

services:
  organizr:
    image: linuxserver/organizr
    container_name: organizr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ./config:/config
    expose:
      - '80'
    restart: unless-stopped

networks:
    default:
      external:
        name: primary
