version: '3'
services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    expose:
      - 9000
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:

networks:
  default:
    external:
      name: primary