version: '3'
services:
  netdata:
    image: netdata/netdata
    container_name: netdata
    hostname: ${HOST_FQDN} # set to fqdn of host
    expose:
      - 19999
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - netdataconf:/etc/netdata
      - netdataweb:/usr/share/netdata/web
      - /etc/letsencrypt/live/ediary.es/fullchain.pem:/etc/netdata/ssl/cert.pem
      - /etc/letsencrypt/live/ediary.es/privkey.pem:/etc/netdata/ssl/key.pem

volumes:
  netdatalib:
  netdatacache:
  netdataconf:
    driver_opts:
      type: none
      device: /home/user/Docker/netdata/conf # Update with the correct path
      o: bind
  netdataweb:
    driver_opts:
      type: none
      device: /home/user/Docker/netdata/web # Update with the correct path
      o: bind

networks:
  default:
    external:
      name: primary