version: "3"
services:

  wikijs-db:
    image: postgres:11-alpine
    container_name: wikijs-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijspostgrespass
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    volumes:
      - ./data:/var/lib/postgresql/data

  wiki:
    image: requarks/wiki:2
    container_name: wikijs
    restart: unless-stopped
    depends_on:
      - wikijs-db
    environment:
      DB_TYPE: postgres
      DB_HOST: wikijs-db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijspostgrespass
      DB_NAME: wiki
    expose:
      - '3000'

networks:
  default:
    name: primary
    external: true