version: '2.4'

services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper
    volumes:
      - /var/volumes/mrwcloud/zookeeper:/tmp/zookeeper
    ports:
      - "2181:2181"
  kafka:
    depends_on:
      - zookeeper
    image: wurstmeister/kafka:2.11-2.0.0
    container_name: kafka
    ports:
      - "9090:9090"
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://kafka:9090,EXTERNAL://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9090,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/volumes/kafka:/opt/kafka/logs

