version: '3'
services:
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: npm
    restart: always
    ports:
      - '81:81' # After first run, this port can be forwarded by the own nginx-proxy-manager to add more security
      - '80:80'
      - '443:443'
    environment:
      DB_MYSQL_HOST: "npm-db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
    volumes:
      - ./config.json:/app/config/production.json
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

  npm-db:
    image: 'jc21/mariadb-aria:latest'
    container_name: npm-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - ./data/mysql:/var/lib/mysql

networks:
  default:
    name: primary
    external: true

# If you want to create the network for the proxy, uncomment the following lines
# Otherwise you can create it manually with the following command:
#     docker network create --driver=bridge --subnet=172.22.0.0/16 primary
# networks:
#   primary:
#     driver: bridge
#     ipam:
#       driver: default
#       config:
#         - subnet: 172.22.0.0/16
#         # gateway: 172.22.0.1
